### ISSUE TITLE
Impossible to inject quality settings

### ISSUE THREAD

**Issue by gatisl** [hrevert/HtImgModule#22]
Default value of Imagine jpg quality is too low and there is no way to configure quality settings through HtImgModule.

Imagine accepts such options for save method
http://imagine.readthedocs.org/en/latest/usage/introduction.html#save-images

I suppose CacheManager::createCache() would be the right place to modify in order to achieve desired behaviour
```
    public function createCache($relativeName, $filter, ImageInterface $image, $formatOrImage = null)
    {
        $cachePath = $this->getCachePath($relativeName, $filter, $formatOrImage);
        //...
        //there must be way to inject $options through htimg configuration
        $image->save($cachePath, $options);
    }
```

**Comment by ojhaujjwal** [comment]
Fixed by #23 and new release 0.4.0!
