### ISSUE TITLE
Trouble image extension uppercase

### ISSUE THREAD

**Issue by MaxVoronov** [hrevert/HtImgModule#26]
Hi @ojhaujjwal ,

I found the following problem. Adding image with extension in the uppercase (for example, *.JPG), we get an exception "A field name was provided without a field value." > header('Content-type', NULL).

Investigate the problem I guess the problem in this method:
https://github.com/hrevert/HtImgModule/blob/master/src/View/Strategy/ImageStrategy.php#L110

One solution to the problem - add strtolower to variable $format.
Another solution -  add option 'format' => 'jpeg' to config. But unfortunately, this option is not specified in the documentation.

Regards

**Comment by ojhaujjwal** [comment]
`return $mimeTypes[strtolower($format)];` should be enough. Do you mind sending a PR?
